name: Deploy Bicep file



jobs:

  azure:
    runs-on: ubuntu-latest
    steps:

    - name: Log into Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v2
      with:
        scope: subscription
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION }}
        template: ./bicep/main.bicep
        parameters: ./bicep/parameters.json environment=${{ env.environment }}
        failOnStdErr: true 

    - name: logout
      run: |
        az logout
    