name: CI + CD

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: []
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_SUBSCRIPTION: "sub-"
  LOCATION: westeurope  

jobs:
  DeployDev:
    name: Deploy to Dev
    if: github.event_name == 'pull_request'
    uses: thepercival/azure-cdk/.github/workflows/azure-deployment.yml@feature/reusableworkflow
    with:
      AZURE_SUBSCRIPTION: ${{ vars.AZURE_SUBSCRIPTION }}
      LOCATION: westeurope
      environment: acc
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  
  DeployAcc:
    name: Deploy to Acc 
    if: github.event_name == 'pull_request'
    uses: thepercival/azure-cdk/.github/workflows/azure-deployment.yml@feature/reusableworkflow    
    with:
      AZURE_SUBSCRIPTION: ${{ vars.AZURE_SUBSCRIPTION }}
      LOCATION: westeurope
      environment: acc
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

   

  # DeployStaging:
  #   name: Deploy to Staging 
  #   if: github.event.ref == 'refs/heads/main'
  #   needs: [Build]
  #   runs-on: ubuntu-latest
  #   environment: "sub-${{ vars.AZURE_SUBSCRIPTION }}-acc"
  #   steps:
  #     - name: Deploy
  #       run: echo I am deploying to acc! 

  # DeployProd:
  #   name: Deploy to Production 
  #   needs: [DeployStaging]
  #   runs-on: ubuntu-latest
  #   environment: "sub-${{ vars.AZURE_SUBSCRIPTION }}-prd"
  #   steps:
  #     - name: Deploy
  #       run: echo I am deploying to prod! 