name: CI + CD

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: []
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_SUBSCRIPTION_BASENAME: "sub-${{ vars.AZURE_SUBSCRIPTION }}"

jobs:
  DeployDev:
    name: Deploy to Dev 
    # if: github.event_name == 'pull_request'
    # needs: [Build]
    runs-on: ubuntu-latest
    environment: "github-azure-${{ vars.AZURE_SUBSCRIPTION }}-dev"
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Log into Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Bicep file
        uses: azure/arm-deploy@v2
        with:
          scope: subscription
          region:  West Europe
          subscriptionId: "${{ env.AZURE_SUBSCRIPTION_BASENAME }}-dev"
          template: ./bicep/main.bicep
          parameters: ./bicep/parameters.json environment=dev
          failOnStdErr: true 
      - name: logout
        run: |
          az logout
    
  # DeployStaging:
  #   name: Deploy to Staging 
  #   if: github.event.ref == 'refs/heads/main'
  #   needs: [Build]
  #   runs-on: ubuntu-latest
  #   environment: "sub-${{ vars.AZURE_SUBSCRIPTION }}-acc"
  #   steps:
  #     - name: Deploy
  #       run: echo I am deploying to acc! 

  # DeployProd:
  #   name: Deploy to Production 
  #   needs: [DeployStaging]
  #   runs-on: ubuntu-latest
  #   environment: "sub-${{ vars.AZURE_SUBSCRIPTION }}-prd"
  #   steps:
  #     - name: Deploy
  #       run: echo I am deploying to prod! 