name: CI + CD

permissions:
  id-token: write
  contents: read

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches: [ main ]
    #workflow_dispatch:
    types:
      - closed

jobs:
  DeployDev:
    name: Deploy to Dev
    uses: thepercival/azure-cdk/.github/workflows/azure-deployment.yml@feature/reusableworkflow
    with:
      AZURE_SUBSCRIPTION: ${{ vars.AZURE_SUBSCRIPTION }}
      LOCATION: westeurope
      environment: dev
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  
  DeployAcc:
    name: Deploy to Acc 
    if: github.event_name == 'pull_request' || github.event.pull_request.merged == true
    needs: [DeployDev]
    uses: thepercival/azure-cdk/.github/workflows/azure-deployment.yml@feature/reusableworkflow    
    with:
      AZURE_SUBSCRIPTION: ${{ vars.AZURE_SUBSCRIPTION }}
      LOCATION: westeurope
      environment: acc
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  DeployPrd:
    name: Deploy to Prd
    if: github.event.pull_request.merged == true
    needs: [DeployAcc]
    uses: thepercival/azure-cdk/.github/workflows/azure-deployment.yml@feature/reusableworkflow    
    with:
      AZURE_SUBSCRIPTION: ${{ vars.AZURE_SUBSCRIPTION }}
      LOCATION: westeurope
      environment: prd
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}   